version: "3.7"

services:
  code-editor:
    image: glazzess/borealys-editor:latest
    container_name: codeeditor
    ports:
    - 3000:3000

  borealys:
    build: "."
    container_name: borealys
    depends_on:
      - cache
    cap_add:
      - LINUX_IMMUTABLE

  cache:
    image: redis:6.2.4-alpine
    container_name: cache