version: "3.7"

services:
  borealys:
    build: "."
    container_name: borealys
    ports:
    - 5000:5000
    depends_on:
      - cache

  cache:
    image: redis:6.2.4-alpine
    container_name: cache